<x-layouts.simple>

    <x-slot name="title">
        {{ __('Privacy Policy') }}
    </x-slot>

    <x-heading.h1 class="md:text-4xl! text-4xl! pt-4 pb-6">
        {{ __('Privacy Policy') }}
    </x-heading.h1>

    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} ({{ __('"us", "we", or "our"') }}) {{ __('operates the') }} {{ config('app.url', '') }} {{ __('website (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.') }}
    </p>

    <p class="mb-6">
        {{ __('We will not use or share your information with anyone except as described in this Privacy Policy.') }}
    </p>

    <p class="mb-6">
        {{ __('We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible at') }} <a href="{{route('terms-of-service')}}" class="text-primary-600 hover:underline">{{ __('terms of service') }}</a>.
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Definitions') }}
    </x-heading.h2>
    
    <p class="mb-4">
        <strong>{{ __('Personal Data') }}:</strong> {{ __('Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Educational Lead Data') }}:</strong> {{ __('Information about prospective students including contact details, academic interests, course preferences, and communication history collected through our CRM system.') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Usage Data') }}:</strong> {{ __('Data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Cookies') }}:</strong> {{ __('Small pieces of data stored on a User\'s device.') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Data Controller') }}:</strong> {{ __('A person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Data Processor (or Service Provider)') }}:</strong> {{ __('Any person (other than an employee of the Data Controller) who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.') }}
    </p>
    
    <p class="mb-4">
        <strong>{{ __('Data Subject') }}:</strong> {{ __('Any living individual who is the subject of Personal Data.') }}
    </p>
    
    <p class="mb-6">
        <strong>{{ __('User') }}:</strong> {{ __('The individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.') }}
    </p>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Information Collection And Use') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('We collect several different types of information for various purposes to provide and improve our Service to you.') }}
    </p>
    
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Personal Data') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:') }}
    </p>
    <ul class="list-disc list-inside mb-6 ml-4">
        <li>{{ __('Email address') }}</li>
        <li>{{ __('First and last name') }}</li>
        <li>{{ __('Phone number') }}</li>
        <li>{{ __('Academic interests and course preferences') }}</li>
        <li>{{ __('Educational background') }}</li>
        <li>{{ __('Cookies and usage data') }}</li>
    </ul>
    <p class="mb-6">
        {{ __('We may use your Personal Data to contact you with newsletters, marketing or promotional materials about educational programs and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.') }}
    </p>
    
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Educational Lead Data') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('As an educational CRM platform, we collect and process information about prospective students (leads) on behalf of educational institutions. This may include:') }}
    </p>
    <ul class="list-disc list-inside mb-6 ml-4">
        <li>{{ __('Contact information (name, email, phone)') }}</li>
        <li>{{ __('Course and program interests') }}</li>
        <li>{{ __('Academic background and qualifications') }}</li>
        <li>{{ __('Communication preferences and history') }}</li>
        <li>{{ __('Enrollment status and sales phase') }}</li>
        <li>{{ __('Marketing source and campaign data (UTM parameters)') }}</li>
    </ul>
    <p class="mb-6">
        {{ __('This data is processed on behalf of our clients (educational institutions) who are the data controllers for their respective leads. We act as a data processor and only use this information to provide our CRM services.') }}
    </p>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Usage Data') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('We may also collect information about how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer\'s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Tracking & Cookies Data') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.') }}
    </p>
    <p class="mb-6">
        {{ __('Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.') }}
    </p>
    <p class="mb-6">
        {{ __('You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.') }}
    </p>
    
    <p class="mb-4 font-semibold">{{ __('Examples of Cookies we use:') }}</p>

    <ul class="list-disc list-inside mb-6 ml-4">
        <li><strong>{{ __('Session Cookies') }}:</strong> {{ __('We use Session Cookies to operate our Service.') }}</li>
        <li><strong>{{ __('Preference Cookies') }}:</strong> {{ __('We use Preference Cookies to remember your preferences and various settings.') }}</li>
        <li><strong>{{ __('Security Cookies') }}:</strong> {{ __('We use Security Cookies for security purposes.') }}</li>
        <li><strong>{{ __('Analytics Cookies') }}:</strong> {{ __('We use Analytics Cookies to track user behavior and improve our Service.') }}</li>
    </ul>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Customer Data (Educational Institutions)') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('Customer Data may include, without limitation, personal information such as names, email addresses, and phone numbers of your prospective students (leads), enrolled students, and other users. Information may be input into the Service by you or collected through integrations with your websites, landing pages, and other marketing properties.') }}
    </p>
    <p class="mb-6">
        {{ __('We will only process Customer Data for the purposes set forth in your agreement with us for the provisioning of the CRM Service. As a data processor, we implement strict security measures and tenant isolation to ensure your data remains private and secure.') }}
    </p>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Use of Data') }}
    </x-heading.h2>
    <p class="mb-4">
        {{ config('app.name', 'Leads-Edu') }} {{ __('uses the collected data for various purposes:') }}
    </p>
    <ul class="list-disc list-inside mb-6 ml-4">
        <li>{{ __('To provide and maintain our CRM Service') }}</li>
        <li>{{ __('To notify you about changes to our Service') }}</li>
        <li>{{ __('To allow you to participate in interactive features of our Service when you choose to do so') }}</li>
        <li>{{ __('To provide customer support') }}</li>
        <li>{{ __('To gather analysis or valuable information so that we can improve our Service') }}</li>
        <li>{{ __('To monitor the usage of our Service') }}</li>
        <li>{{ __('To detect, prevent and address technical issues') }}</li>
        <li>{{ __('To manage and track educational leads on behalf of our clients') }}</li>
        <li>{{ __('To facilitate communication between educational institutions and prospective students') }}</li>
        <li>{{ __('To generate reports and analytics about lead conversion and enrollment') }}</li>
        <li>{{ __('To provide you with news, special offers and general information about educational programs and services which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information') }}</li>
    </ul>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Retention of Data') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} {{ __('will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.') }}
    </p>
    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} {{ __('will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Transfer Of Data') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.') }}
    </p>

    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} {{ __('will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Business Transaction') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('If') }} {{ config('app.name', 'Leads-Edu') }} {{ __('is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Disclosure for Law Enforcement') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('Under certain circumstances,') }} {{ config('app.name', 'Leads-Edu') }} {{ __('may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Legal Requirements') }}
    </x-heading.h2>
    <p class="mb-4">
        {{ config('app.name', 'Leads-Edu') }} {{ __('may disclose your Personal Data in the good faith belief that such action is necessary to:') }}
    </p>
    <ul class="list-disc list-inside mb-6 ml-4">
        <li>{{ __('To comply with a legal obligation') }}</li>
        <li>{{ __('To protect and defend the rights or property of') }} {{ config('app.name', 'Leads-Edu') }}</li>
        <li>{{ __('To prevent or investigate possible wrongdoing in connection with the Service') }}</li>
        <li>{{ __('To protect the personal safety of users of the Service or the public') }}</li>
        <li>{{ __('To protect against legal liability') }}</li>
    </ul>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Security Of Data') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.') }}
    </p>
    
    <p class="mb-6">
        {{ __('We implement industry-standard security measures including encryption, secure data centers, regular security audits, and strict access controls. All data is isolated by tenant to ensure complete privacy between educational institutions.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2">
            “Do Not Track” Signals
    </x-heading.h2>

    <p class="mb-6">
            We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
    </p>
    <p class="mb-6">
            You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
    </p>
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Your Rights') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} {{ __('aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.') }}
    </p>
    <p class="mb-6">
        {{ __('Whenever made possible, you can update your Personal Data directly within your account settings section. If you are unable to change your Personal Data, please contact us to make the required changes.') }}
    </p>
    <p class="mb-6">
        {{ __('If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.') }}
    </p>
    <p class="mb-4">
        {{ __('In certain circumstances, you have the right:') }}
    </p>
    <ul class="list-disc list-inside mb-6 ml-4">
        <li>{{ __('To access and receive a copy of the Personal Data we hold about you') }}</li>
        <li>{{ __('To rectify any Personal Data held about you that is inaccurate') }}</li>
        <li>{{ __('To request the deletion of Personal Data held about you') }}</li>
        <li>{{ __('To object to processing of your Personal Data') }}</li>
        <li>{{ __('To request restriction of processing your Personal Data') }}</li>
        <li>{{ __('To request transfer of your Personal Data') }}</li>
        <li>{{ __('To withdraw consent at any time') }}</li>
    </ul>
    <p class="mb-6">
        {{ __('You have the right to data portability for the information you provide to') }} {{ config('app.name', 'Leads-Edu') }}. {{ __('You can request to obtain a copy of your Personal Data in a commonly used electronic format so that you can manage and move it.') }}
    <p class="mb-6">
        {{ __('Please note that we may ask you to verify your identity before responding to such requests.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Service Providers') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.') }}
    </p>
    <p class="mb-6">
        {{ __('These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Analytics') }}
    </x-heading.h2>
    <p class="mb-6">
        {{ __('We may use third-party Service Providers to monitor and analyze the use of our Service.') }}
    </p>
    <x-heading.h3 class="text-lg mb-2 font-semibold">
        {{ __('Google Analytics') }}
    </x-heading.h3>

    <p class="mb-6">
        {{ __('Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.') }}
    </p>
    <p class="mb-6">
        {{ __('You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity. For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page.') }}
    </p>

    <x-heading.h3 class="text-lg mb-2 font-semibold">
        {{ __('Behavioral Remarketing') }}
    </x-heading.h3>

    <p class="mb-6">
        {{ config('app.name', 'Leads-Edu') }} {{ __('uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.') }}
    </p>

    <x-heading.h3 class="text-lg mb-2 font-semibold">
        {{ __('Google AdWords') }}
    </x-heading.h3>

    <p class="mb-6">
        {{ __('Google AdWords remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page. Google also recommends installing the Google Analytics Opt-out Browser Add-on for your web browser. Google Analytics Opt-out Browser Add-on provides visitors with the ability to prevent their data from being collected and used by Google Analytics. For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page.') }}
    </p>

    <x-heading.h3 class="text-lg mb-2 font-semibold">
        {{ __('Facebook') }}
    </x-heading.h3>

    <p class="mb-6">
        {{ __('Facebook remarketing service is provided by Facebook Inc. You can learn more about interest-based advertising from Facebook by visiting this page. To opt-out from Facebook\'s interest-based ads follow these instructions from Facebook. Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the Digital Advertising Alliance in the USA, the Digital Advertising Alliance of Canada, or the European Interactive Digital Advertising Alliance in Europe, or opt-out using your mobile device settings.') }}
    </p>
    <p class="mb-6">
        {{ __('For more information on the privacy practices of Facebook, please visit Facebook\'s Data Policy.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Payments') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information. The payment processor we work with is Stripe. Their Privacy Policy can be viewed here.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Links To Other Sites') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party\'s site. We strongly advise you to review the Privacy Policy of every site you visit.') }}
    </p>
    <p class="mb-6">
        {{ __('We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.') }}
    </p>

    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Children\'s Privacy') }}
    </x-heading.h2>
    
    <p class="mb-6">
        {{ __('Our Service does not address anyone under the age of 13 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.') }}
    </p>
    
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Changes To This Privacy Policy') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the "effective date" at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.') }}
    </p>
    
    <x-heading.h2 class="text-xl mb-2 font-semibold">
        {{ __('Contact Us') }}
    </x-heading.h2>

    <p class="mb-6">
        {{ __('If you have any questions about this Privacy Policy, please contact us at') }} <a href="mailto:{{ config('app.support_email', '') }}" class="text-primary-600 hover:underline">{{ config('app.support_email', '') }}</a>.
    </p>


</x-layouts.simple>
